spring:
  config:
    import: optional:file:.env[.properties]
  sequence:
    pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
    proxy: true

graphql:
  client:
    GLOBAL:
      address: http://10.7.5.4:30881/graphql